
export const products =[
    {
        id:"1",
        title: "A15",
        price: "299.999",
        stock: 12,
        descripcion: "descripcion del producto",
        category: "Samsung",
        img: "https://res.cloudinary.com/dukvp5o4s/image/upload/v1727828723/uvmve4kgemr0ynmuvvn0.png",
    },
    {
        id:"2",
        title: "blade 50v",
        price: "264.999",
        stock: 6,
        descripcion: "descripcion del producto2",
        category: "ZTE",
        img: "https://res.cloudinary.com/dukvp5o4s/image/upload/v1727828730/w8pxmijoavvug9vcbn89.png",
    },
    {
        id:"3",
        title: "A3",
        price: "294.999",
        stock: 10,
        descripcion: "descripcion del producto3",
        category: "xiaomi",
        img: "https://res.cloudinary.com/dukvp5o4s/image/upload/v1727828730/rcjzfszdkuzokavfzizp.png",
    },
    {
        id:"4",
        title: "A23",
        price: "699.999",
        stock: 3,
        descripcion: "descripcion del producto4",
        category: "Samsung",
        img: "https://res.cloudinary.com/dukvp5o4s/image/upload/v1727828729/ehjsutofedrhdl4adib9.png",
    },
    {
        id:"5",
        title: "G24",
        price: "289.999",
        stock: 22,
        descripcion: "descripcion del producto5",
        category: "Motorola",
        img: "https://res.cloudinary.com/dukvp5o4s/image/upload/v1727828732/anh23lemprbqqtkoevrs.png",
    },

    /////////////////////////////
    {
        id:"6",
        title: "TCL 403",
        price: "239.999",
        stock: 111,
        descripcion: "descripcion del producto6",
        category: "TCL",
        img: "https://res.cloudinary.com/dukvp5o4s/image/upload/v1728102620/jpbirf5zekeonh5p0a6g.png",
    },
    {
        id:"7",
        title: "TCL 405",
        price: "450.999",
        stock: 44,
        descripcion: "descripcion del producto7",
        category: "TCL",
        img: "https://res.cloudinary.com/dukvp5o4s/image/upload/v1728102621/xlxoftblclb1doerkxc1.png",
    },
    {
        id:"8",
        title: "S23 FE",
        price: "1.299.999",
        stock: 34,
        descripcion: "descripcion del producto8",
        category: "Samsung",
        img: "https://res.cloudinary.com/dukvp5o4s/image/upload/v1728102582/kdcqrpuri75idtno83eg.png",
    },
    {
        id:"9",
        title: "TCL 408",
        price: "145.00",
        stock: 24,
        descripcion: "descripcion del producto9",
        category: "Samsung",
        img: "https://res.cloudinary.com/dukvp5o4s/image/upload/v1728102620/hcrs8wq6czqw1kg8t3uv.png",
    },
    {
        id:"10",
        title: "Flip 5",
        price: "1.645.999",
        stock: 44,
        descripcion: "descripcion del producto10",
        category: "Samsung",
        img: "https://res.cloudinary.com/dukvp5o4s/image/upload/v1728103171/akwxa6fykjytdjar2qgy.png",
    },
];